<?php
	/**
	 * sc2ranks.com / drupal user profile integration module
	 * @author Ameer Ayoub <ameer.ayoub@gmail.com>
	 */
	include("lib/sc2ranks.php"); // Include sc2ranks api library
	
	/**
	 * Helper function, replaces info in database with new data and returns new
	 * data.
	 * @param int $uid the user to whose information to update
	 * @return object the user sc2ranks data object, as mapped from the schema
	 */
	function helper_update_sc2ranks($uid, $is_new = TRUE){ 
		// One week
		$cache_expiration = 60*variable_get("sc2ranks_cache_expiration", 60*24*7);
		$current_time = time();							// Now, to calc cache
		// The profile field for character region
		$region_profile_field = variable_get("sc2ranks_region_profile_field", "profile_character_region");
		// The profile field for character name
		$name_profile_field = variable_get("sc2ranks_name_profile_field", "profile_character_name");
		// The profile field for character code
		$code_profile_field = variable_get("sc2ranks_code_profile_field", "profile_character_code");
		$app_key = variable_get("sc2ranks_app_key", null);
		$current_time = time();
		$debug = FALSE;
		 
		$char_region = "";
		$char_name = "";
		$char_code = 0;
		
		// Get the data from the db table
		// Build the query to get the user's bnet info
		$result = db_query(
			'SELECT {profile_fields}.name, {profile_values}.value
			FROM {profile_values}
			LEFT JOIN {profile_fields} ON {profile_values}.fid = {profile_fields}.fid
			WHERE {profile_values}.uid = %d
			AND {profile_fields}.name IN (\'%s\', \'%s\', \'%s\')',
			$uid, $name_profile_field, $code_profile_field, $region_profile_field);

		while ($char_info = db_fetch_object($result)){
			switch ($char_info->name){
				case $name_profile_field:
					$char_name = $char_info->value;
					break;
				case $code_profile_field:
					$char_code = $char_info->value;
					break;
				case $region_profile_field:
					$char_region = $char_info->value;
					break;
				default:
					drupal_set_message("db_fetch_object returned unknown character information object format.", "error");
					return null;
			}
		}
				
		if (strlen($char_region) == 0 || strlen($char_name) == 0 || $char_code == 0){
			drupal_set_message(t("There is information missing from the profile."), "error");
			return null;
		}
		
		// Update the data from the sc2ranks site
		$request = new sc2ranks_request($app_key);
		$new_char_data = $request->get_character_data($char_name, $char_code, $char_region);
		$new_team_data = $request->get_bracket_data();
		
		// pack the info
		$to_save = array(
			'uid' => $uid,
			'character_name' => $char_name,
			'character_code' => $char_code,
			'league' => $new_team_data[0]->league,
			'points' => $new_team_data[0]->points,
			'division' => $new_team_data[0]->division,
			'wins' => $new_team_data[0]->wins,
			'loses' => $new_team_data[0]->losses,
			'fav_race' => $new_team_data[0]->fav_race,
			'bnet_id'	=> $new_char_data->bnet_id,
			'modified' => $current_time);
		// Insert or update into database
		if($is_new)
		{
			if($debug) drupal_set_message("Writing data to table as new.");
			drupal_write_record("cache_sc2ranks", $to_save);
		} else {
			if($debug) drupal_set_message("Writing data to table as update.");
			drupal_write_record("cache_sc2ranks", $to_save, $uid);
		}
		// Select what we just inserted
		$result = db_query('SELECT * FROM {cache_sc2ranks} WHERE uid = %d', $uid);
		if($data = db_fetch_object($result)){
			return $data;
		} else {
			drupal_set_message("error requerying database.", "warning");
			return null;
		}
	}
	
	/**
	 * Helper function, checks if sc2ranks data in database is not expired, if
	 * not then it returns the data from database otherwise updates info in db
	 * and returns the updated info.
	 * @param int $uid the drupal user id of the user who's record we want
	 * @return object the user sc2ranks data object, as mapped from the schema
	 */
	function helper_get_sc2ranks($uid){
		 // One week
		$cache_expiration = 60*variable_get("sc2ranks_cache_expiration", 60*24*7);
		$current_time = time();							// Now, to calc cache
		// The profile field for character name
		$name_profile_field = variable_get("sc2ranks_name_profile_field", "profile_character_name");
		// The profile field for character code
		$code_profile_field = variable_get("sc2ranks_code_profile_field", "profile_character_code");
		$debug = FALSE;
		
		$result = db_query('SELECT * FROM {cache_sc2ranks} WHERE uid = %d', $uid);
		// Refer to sc2ranks.install for database schema
		if($user = db_fetch_object($result)){
			if (($user->modified - $current_time) >= $cache_expiration){
				if($debug) drupal_set_message("Updating cached data.");
				return helper_update_sc2ranks($user->uid, FALSE);
			} else {
				// Data is valid
				if($debug) drupal_set_message("Using cached data.");
				return $user;
			}
		} else {
			// User not in cache database
			// Create new cache entry if user has bnet info
			if($debug) drupal_set_message("Creating new object.");
			return helper_update_sc2ranks($uid);
		}
	}
	
	/**
	 * Implemenation of hook_views_api
	 */
	function sc2ranks_views_api() {
		return array(
			'api' => 2,
			'path' => drupal_get_path('module', 'sc2ranks'),
		);
	}
	
	/**
	 * Implementation of hook_perm()
	 */
	function sc2ranks_perm(){
		return array('view sc2ranks records', 'administer sc2ranks module', 'access character code');
	}

	/**
	 * Implementation of hook_theme()
	 */
	function sc2ranks_theme() {
		return array(
			'profile_sc2ranks' => array(
				'template' => 'profile-sc2ranks',
				'arguments' => array('record_data' => NULL),
			),
		);
	}
	
	/**
	 * Implementation of preprocess_theme_hook()
	 */
	function template_preprocess_profile_sc2ranks(&$variables){
		if($variables['record_data']){
			$variables['show_code'] = (bool) db_result(db_query('SELECT fid FROM {profile_fields} WHERE name = \'%s\' AND visibility NOT IN (%d, %d)', array(variable_get("sc2ranks_code_profile_field", "profile_character_code"), PROFILE_PRIVATE, PROFILE_HIDDEN)));

			$variables['sc2ranks_profile_url'] = 'http://www.sc2ranks.com/' .
			$variables['record_data']->region . '/' .
			$variables['record_data']->bnet_id . '/' .
			$variables['record_data']->character_name . '/';
			
			$variables['bnet_profile_url'] = 'http://' .
			$variables['record_data']->region . '.battle.net/sc2/en/profile/' .
			$variables['record_data']->bnet_id . '/1/' . 
			$variables['record_data']->character_name . '/';
			
			$variables['league_image_url'] = base_path() . 
			drupal_get_path('module', 'sc2ranks') . "/images/icon-rank-" .
			$variables['record_data']->league . ".png";
			
			$variables['race_image_url'] = base_path() . 
			drupal_get_path('module', 'sc2ranks') . "/images/icon-race-" .
			$variables['record_data']->fav_race . ".jpg";
			
			$variables['sc2ranks_icon_url'] = base_path() . 
			drupal_get_path('module', 'sc2ranks') . "/images/sc2ranks-icon.png";
			
			$variables['bnet_icon_url'] = base_path() . 
			drupal_get_path('module', 'sc2ranks') . "/images/bnet-icon.png";
			
			if($variables['losses'] == 0){
				$variables['ratio'] = 100;
			} else {
				$variables['ratio'] = $variables['wins']/$variables['losses'];
			}
		}
	}
	
	/**
	 * Implementation of hook_profile_alter()
	 * Adds user to cache table is creating a new user, Checks if the user data
	 * is up to date if displaying user info on a profile.
	 */
	function sc2ranks_profile_alter(&$account){
		// If user account being viewed then let's append our data
		if(user_access("view sc2ranks records")){
			$uid = $account->uid;
			$account_data = helper_get_sc2ranks($uid);
			$account->content['summary']['sc2ranks'] = array(
				'#type' => t('user_profile_item'),
				'#title' => t('Battle.net Record'),
				'#value' => theme("profile_sc2ranks", $account_data)
			);
		}
	}

	/**
	 * Implementation of hook_admin()
	 */
	function sc2ranks_admin() {
		$form = array(
			'sc2ranks_app_key' => array(
				'#type'	=> 'textfield',
				'#title' => 'sc2ranks.com API app key',
				'#default_value' => variable_get('sc2ranks_app_key', $_SERVER['SERVER_NAME']),
				'#size' => 63,
				'#maxlength' => 255,
				'#description' => 'The api key for sc2ranks.com, should just be your site name, any key is valid.',
				'#required' => FALSE
			),
			'sc2ranks_region_profile_field' => array(
				'#type'	=> 'textfield',
				'#title' => 'Character name profile field',
				'#default_value' => variable_get('sc2ranks_region_profile_field', "profile_character_region"),
				'#size' => 63,
				'#maxlength' => 255,
				'#description' => 'The field you created using the profile module to hold a player\'s BNET character region.',
				'#required' => TRUE
			),
			'sc2ranks_name_profile_field' => array(
				'#type'	=> 'textfield',
				'#title' => 'Character name profile field',
				'#default_value' => variable_get('sc2ranks_name_profile_field', "profile_character_name"),
				'#size' => 63,
				'#maxlength' => 255,
				'#description' => 'The field you created using the profile module to hold a player\'s BNET character name.',
				'#required' => TRUE
			),
			'sc2ranks_code_profile_field' => array(
				'#type'	=> 'textfield',
				'#title' => 'Character code profile field',
				'#default_value' => variable_get('sc2ranks_code_profile_field', "profile_character_code"),
				'#size' => 63,
				'#maxlength' => 255,
				'#description' => 'The field you created using the profile module to hold a player\'s BNET character code.',
				'#required' => TRUE
			),
			'sc2ranks_cache_expiration' => array(
				'#type'	=> 'textfield',
				'#title' => 'Cache expiration time',
				'#default_value' => variable_get('sc2ranks_cache_expiration', 60*24*7),
				'#size' => 11,
				'#maxlength' => 11,
				'#description' => 'Number of minutes to keep character data cached.',
				'#required' => FALSE
			),
		);
		
		return system_settings_form($form);
	}
	
	/**
	 * Implementation of hook_menu()
	 */
	function sc2ranks_menu() {
		$items = array();
		$items['admin/settings/sc2ranks'] = array(
			'title' => 'Sc2ranks settings',
			'description' => 'Set profile field names, api key, and cache settings for the sc2ranks module.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('sc2ranks_admin'),
			'access arguments' => array('administer sc2ranks module'),
			'type' => MENU_NORMAL_ITEM,
		);
		return $items;
	}
